// Emoji sentiment map
const EmojiSentimentMap = {
    "😀": {"tone": "Happy", "score": 2},
    "😢": {"tone": "Sad", "score": -2},
    "😂": {"tone": "Humor", "score": 1},
    "😡": {"tone": "Angry", "score": -3},
    "❤️": {"tone": "Love", "score": 3},
    "💔": {"tone": "Heartbroken", "score": -3},
    "👍": {"tone": "Positive", "score": 2},
    "👎": {"tone": "Negative", "score": -2},
    "👋": {"tone": "Waving", "score": 1},
    "💪": {"tone": "Strong", "score": 2},
    "✌️": {"tone": "Peace", "score": 2},
    "🤚": {"tone": "Restrictive", "score": 1},
    "🤙": {"tone": "Wants You To Make A Call", "score": 2},
    "👌": {"tone": "Perfect", "score": 2},
    "✋": {"tone": "Wanna Be Friendly", "score": 2},
    "🤏": {"tone": "Comparing", "score": 1},
    "🖐️": {"tone": "Open Type", "score": 1},
    "🖖": {"tone": "Giving You A Vulcan Salute", "score": 2},
    "🤝": {"tone": "Wanna Handshake", "score": 2},
    "🙌": {"tone": "Celebrating", "score": 3},
    "👏": {"tone": "Clapping", "score": 2},
    "👐": {"tone": "Friendly", "score": 2},
    "🤲": {"tone": "Offering Something", "score": 2},
    "✊": {"tone": "Swearing", "score": 2},
    "🤜": {"tone": "Fist Bumping", "score": 2},
    "🤛": {"tone": "Fist Bumping", "score": 2},
    "🖊️": {"tone": "Writing", "score": 1},
    "🖌️": {"tone": "Painting", "score": 2},
    "🖕": {"tone": "Being Offensive", "score": -3},
    "😎": {"tone": "Cool", "score": 1},
    "😱": {"tone": "Fear", "score": -2},
    "🤔": {"tone": "Thinking", "score": 0},
    "🥳": {"tone": "Celebration", "score": 2},
    "😴": {"tone": "Sleepy", "score": -1},
    "🤗": {"tone": "Hug", "score": 2},
    "😜": {"tone": "Playful", "score": 1},
    "😇": {"tone": "Innocent", "score": 2},
    "🤩": {"tone": "Excited", "score": 3},
    "😬": {"tone": "Nervous", "score": -1},
    "😔": {"tone": "Disappointed", "score": -2},
    "🤯": {"tone": "Mind Blown", "score": 2},
    "😏": {"tone": "Smirking", "score": 1},
    "🥺": {"tone": "Pleading", "score": -1},
    "😅": {"tone": "Having A Comedic Sense Of Relief", "score": 1},
    "😒": {"tone": "Unfazed", "score": -1},
    "😓": {"tone": "Anxious", "score": -2},
    "😩": {"tone": "Frustrated", "score": -2},
    "😤": {"tone": "Triumphant", "score": 1},
    "😵": {"tone": "Dizzy", "score": -2},
    "🤒": {"tone": "Sick", "score": -2},
    "🤕": {"tone": "Injured", "score": -2},
    "🤑": {"tone": "Money-Minded", "score": 1},
    "🤠": {"tone": "Determined", "score": 1},
    "🤖": {"tone": "Techy", "score": 1},
    "🤧": {"tone": "Sneezy", "score": -1},
    "😷": {"tone": "Allergic", "score": -1},
    "🤤": {"tone": "Drooling", "score": 2},
    "🧐": {"tone": "Curious", "score": 1},
    "🥵": {"tone": "Overwhelmed", "score": -2},
    "🥶": {"tone": "Getting Chills", "score": -2},
    "😺": {"tone": "Happy", "score": 2},
    "😸": {"tone": "Grinning", "score": 2},
    "😻": {"tone": "Admired", "score": 3},
    "😼": {"tone": "Smirking", "score": 1},
    "😽": {"tone": "Lovey-dovey", "score": 2},
    "🙀": {"tone": "Weary", "score": -2},
    "😿": {"tone": "Crying", "score": -2},
    "😾": {"tone": "Pouting", "score": -1},
    "👻": {"tone": "Playful", "score": 0},
    "💩": {"tone": "Shitty", "score": -2},
    "🏆": {"tone": "Ambitious", "score": 3},
    "💡": {"tone": "Innovative", "score": 2},
    "🧘‍♀️": {"tone": "Calm", "score": 2},
    "🎉": {"tone": "Festive", "score": 3},
    "🌊": {"tone": "Relaxing", "score": 2},
    "🎨": {"tone": "Creative", "score": 2},
    "🌟": {"tone": "Inspiring", "score": 2},
    "🔥": {"tone": "Excited", "score": 3},
    "🔒": {"tone": "Locked", "score": -1},
    "📈": {"tone": "Growth", "score": 2},
    "📉": {"tone": "Decline", "score": -2},
    "👩‍👧": {"tone": "Mother and Daughter", "score": 3},
    "👨‍👧": {"tone": "Father and Daughter", "score": 3},
    "👩‍👦": {"tone": "Mother and Son", "score": 3},
    "👨‍👦": {"tone": "Father and Son", "score": 3},
    "👩‍❤️‍👩‍👧": {"tone": "Couple with Daughter", "score": 3},
    "👨‍❤️‍👨‍👦": {"tone": "Couple with Son", "score": 3},
    "👨‍❤️‍👨‍👧‍👦": {"tone": "Couple with Children", "score": 3},
    "👩‍👧‍👧": {"tone": "Mother with Daughters", "score": 3},
    "👨‍👦‍👦": {"tone": "Father with Sons", "score": 3},
    "👩‍👦‍👦": {"tone": "Mother with Sons", "score": 3},
    "👨‍👧‍👧": {"tone": "Father with Daughters", "score": 3},
    "👩‍👧‍👦": {"tone": "Mother with Children", "score": 3},
    "👨‍👧‍👦": {"tone": "Father with Children", "score": 3},
    "🧑‍🦴": {"tone": "Person With A B*ner", "score": 0},
    "😍💖": {"tone": "Infatuated", "score": 5},
    "🤔💭": {"tone": "Thinking About Something Deeply", "score": 1},
    "🤩🌟": {"tone": "Starstruck", "score": 5},
    "😬😅": {"tone": "Awkwardly Relieved", "score": 1},
    "😡🔥": {"tone": "Furious", "score": -4},
    "😢💔": {"tone": "Heartbroken", "score": -4},
    "😎🌊": {"tone": "Cool And Relaxed", "score": 2},
    "😏😈": {"tone": "A Sly Mischief", "score": 2},
    "😏💋": {"tone": "Flirty", "score": 2},
    "😇💖": {"tone": "In Pure Love", "score": 5},
    "😡💥": {"tone": "Explosively Angry", "score": -5},
    "😴💤": {"tone": "In Deep Sleep", "score": -2},
    "🤗🌈": {"tone": "Embracing The peace", "score": 4},
    "😌🌸": {"tone": "Calm And Happy", "score": 3},
    "😡💢": {"tone": "Angry And Irritated", "score": -4},
    "🤗🌻": {"tone": "Giving You A Warm Hug", "score": 4},
    "🌊🏄‍♂️": {"tone": "On A Surfing Adventure", "score": 4},
    "🍕❤️": {"tone": "Has Love for Pizza", "score": 4},
    "🎨🖌️": {"tone": "Expressing Creativity", "score": 4},
    "🧘‍♀️🌿": {"tone": "So Peaceful", "score": 4},
    "🎶💃": {"tone": "On A Dance Party", "score": 5},
    "🤩🎢": {"tone": "Is Excited For A Ride", "score": 5},
    "🍂🍁": {"tone": "Experiencing Autumn Vibes", "score": 3},
    "🌻☀️": {"tone": "Bright And Happy", "score": 4},
    "🏖️🌅": {"tone": "Relaxing On A Beach", "score": 5},
    "🎉🎊": {"tone": "Celebrating With Friends", "score": 5},
    "🎤🎶": {"tone": "Singing With Joy", "score": 4},
    "🧗‍♀️🏔️": {"tone": "On A Climbing Adventure", "score": 5},
    "🌼🌞": {"tone": "Bright And Cheerful", "score": 4},
    "🦄🌌": {"tone": "Experiencingn A Magical Night", "score": 5},
    "🍕🤤": {"tone": "Craving For More Food", "score": 4},
    "🎶💖": {"tone": "Has Love For Music", "score": 5},
    "👻🍬": {"tone": "Giving You Some Spooky Treats", "score": 3},
    "🍰🎉": {"tone": "On A Sweet Celebration", "score": 4},
    "🎸🎻": {"tone": "Playing Musical Instruments", "score": 3},
    "🌌🛸": {"tone": "Exploring The Beauty Of Space", "score": 5},
    "🍩☕": {"tone": "Having A Sweet Morning", "score": 4},
    "🌊🐠": {"tone": "On A Underwater Adventure", "score": 4},
    "🍇🍷": {"tone": "On A Wine and Dine", "score": 4},
    "🐉🔥": {"tone": "Has A Fiery Spirit", "score": 5},
    "🌈🧗‍♀️": {"tone": "Climbing Towards Happiness", "score": 5},
    "🐾❤️": {"tone": "Is Having Pet Love", "score": 5},
    "🚴‍♂️🌳": {"tone": "On A Nature Ride", "score": 4},
};

export default EmojiSentimentMap;