const ReverseMap = {
        "💤 ☕️": "need coffee to wake up",
        "🎉 🎂 🎁": "birthday celebration",
        "🍕 🍔 🍟": "fast food feast",
        "🏖️ 🌊 ☀️": "beach vacation",
        "📚 ☕️ 🌧️": "cozy study session",
        "🏋️‍♂️ 🍗": "workout and protein",
        "🔥 💪": "feeling strong or motivated",
        "❤️ 🥰": "feeling loved",
        "👩‍💻 ☕️ 🎧": "coding with coffee and music",
        "🚗 🎶 🌄": "road trip vibes",
        "🌙 🛌 😴": "good night",
        "🎮 👾 🎧": "gaming session",
        "🐶 🐕 🎾": "playing with dogs",
        "🍿 🎥 🎬": "movie night",
        "📞 ❤️": "love on a call",
        "🧹 🏡 🌟": "cleaning and organizing",
        "🛍️ 💳 😊": "shopping spree",
        "🍎 🍇 🍌": "healthy snacks",
        "🎧 🎤 🎵": "singing or karaoke time",
        "🌟 🙌": "achieving something great",
        "🌮 🌯 🥤": "Mexican food feast",
        "🪴 🌻 ☀️": "gardening day",
        "🖥️ 🖱️ 📊": "work-from-home grind",
        "📷 🌅 🌄": "photography adventure",
        "🌩️ 🌧️ 🌂": "rainy day",
        "🍷 🍝 🕯️": "romantic dinner",
        "🚴‍♂️ 🌳 🌞": "bike ride in nature",
        "🏔️ 🥾 🗻": "hiking adventure",
        "🏠 🛋️ 📺": "lazy day at home",
        "🎓 📜 🎉": "graduation celebration",
        "🐱 🛏️ 🐾": "cat cuddles",
        "🍩 ☕️ 💻": "coffee and donut work session",
        "🥗 🍋 🥑": "healthy meal prep",
        "📦 📮 🛍️": "online shopping delivery",
        "🍫 🍪 🥛": "sweet tooth snack time",
        "🎭 🎨 🎤": "arts and creativity",
        "📱 🔋 🕰️": "phone scrolling for hours",
        "✈️ 🌍 🧳": "travel adventure",
        "📅 📝 🧠": "planning and brainstorming",
        "🏫 📓 ✏️": "school day",
        "🥋 🥊 🥅": "sports practice",
        "🎂 🕯️ 🎶": "birthday song time",
        "🕹️ 🎮 🕛": "gaming all night",
        "🍔 🥤 🚗": "drive-thru meal",
        "🎄 🎁 ❄️": "Christmas vibes",
        "🐝 🌸 🍯": "springtime buzz",
        "🚿 🧴 🛏️": "post-shower relaxation",
        "🤳 💬 📸": "selfie and texting",
        "🍹 🍍 🏖️": "tropical vacation",
        "📀 📼 🎵": "nostalgia trip"
};
  
export default ReverseMap;  