import React from 'react';

const TravelExperience = ({ country, emojis, famousLandmark }) => {
  return (
    <div className="travel-card">
      <h2>{country}</h2>
      <p className="emojis">{emojis}</p>
      <p>Famous: {famousLandmark}</p>
    </div>
  );
};

const VirtualTravel = () => {
  const additionalTravelExperiences = [
    { country: 'Antarctica', emojis: '🇦🇶 ❄️ 🗻', famousLandmark: 'Penguins and Icebergs' },
    { country: 'Arctic', emojis: '🌐 ❄️ 🏔️', famousLandmark: 'Northern Lights' },
    { country: 'Argentina', emojis: '🥩 🍷 🇦🇷', famousLandmark: 'Perito Moreno Glacier' },
    { country: 'Aruba', emojis: '🇦🇼 🏝️ ⛰️', famousLandmark: 'California Lighthouse' },
    { country: 'Australia', emojis: '🦘 🏖️ 🐨', famousLandmark: 'Sydney Opera House' },
    { country: 'Albania', emojis: '🇦🇱 🏞️ 🏰', famousLandmark: 'Gjirokastër Castle' },
    { country: 'Austria', emojis: '🇦🇹 ⛰️ 🏰', famousLandmark: 'Schönbrunn Palace' },
    { country: 'Armenia', emojis: '🇦🇲 🏰 🍇', famousLandmark: 'Tatev Monastery' },
    { country: 'Azerbaijan', emojis: '🇦🇿 🔥 🏰', famousLandmark: 'Gobustan National Park' },
    { country: 'Andorra', emojis: '🇦🇩 ⛰️ 🏰', famousLandmark: 'Vallnord' },
    { country: 'Algeria', emojis: '🇩🇿 🏜️ 🏛️', famousLandmark: 'Timgad' },
    { country: 'Angola', emojis: '🇦🇴 🏞️ 🐘', famousLandmark: 'Tunda Vala Fissure' },
    { country: 'Antigua and Barbuda', emojis: '🇦🇬 🏝️ ⛵', famousLandmark: 'Shirley Heights' },
    { country: 'Afghanistan', emojis: '🇦🇫 🏔️ 🕌', famousLandmark: 'Bamiyan Valley' },
    { country: 'Bangladesh', emojis: '🇧🇩 🌍 🏞️', famousLandmark: 'Sundarbans Mangrove Forest' },
    { country: 'Belize', emojis: '🇧🇿 🏝️ 🐚', famousLandmark: 'Great Blue Hole' },
    { country: 'Botswana', emojis: '🇧🇼 🏞️ 🦓', famousLandmark: 'Okavango Delta' },
    { country: 'Brunei', emojis: '🇧🇳 🏞️ 🕌', famousLandmark: 'Omar Ali Saifuddien Mosque' },
    { country: 'Bhutan', emojis: '🇧🇹 🏞️ 🏰', famousLandmark: 'Taktsang Palphug Monastery' },
    { country: 'Bolivia', emojis: '🇧🇴 🏔️ 🌋', famousLandmark: 'Salar de Uyuni' },
    { country: 'Bahrain', emojis: '🇧🇭 🏝️ 🕌', famousLandmark: 'Tree of Life' },
    { country: 'Brazil', emojis: '🌴 🎉 🍹', famousLandmark: 'Christ the Redeemer' },
    { country: 'Bulgaria', emojis: '🇧🇬 🏰 🌲', famousLandmark: 'Rila Monastery' },
    { country: 'Benin', emojis: '🇧🇯 🌍 🏰', famousLandmark: 'Royal Palaces of Abomey' },
    { country: 'Bosnia and Herzegovina', emojis: '🇧🇦 🏰 🌲', famousLandmark: 'Mostar Bridge' },
    { country: 'Burkina Faso', emojis: '🇧🇫 🌍 🏰', famousLandmark: 'Ruins of Loropéni' },
    { country: 'Barbados', emojis: '🇧🇧 🏝️ 🌊', famousLandmark: 'Harrison\'s Cave' },
    { country: 'Belarus', emojis: '🇧🇾 🏰 🌲', famousLandmark: 'Mir Castle Complex' },
    { country: 'Burundi', emojis: '🇧🇮 🌍 🏞️', famousLandmark: 'Karera Waterfalls' },
    { country: 'Cabo Verde', emojis: '🇨🇻 🏝️ 🌊', famousLandmark: 'Pico do Fogo' },
    { country: 'Cambodia', emojis: '🇰🇭 🏰 🌅', famousLandmark: 'Angkor Wat' },
    { country: 'Cameroon', emojis: '🇨🇲 🌍 🏞️', famousLandmark: 'Rhumsiki Peak' },
    { country: 'Chad', emojis: '🇹🇩 🌍 🏜️', famousLandmark: 'Ennedi Plateau' },
    { country: 'Comoros', emojis: '🇰🇲 🏝️ 🌊', famousLandmark: 'Grand Comore' },
    { country: 'Côte d Ivoire', emojis: '🇨🇮 🌍 🏞️', famousLandmark: 'Mount Nimba Strict Nature Reserve' },
    { country: 'Chile', emojis: '🏔️ 🍇 🇨🇱', famousLandmark: 'Easter Island' },
    { country: 'Czech Republic', emojis: '🏰 🍺 🎻', famousLandmark: 'Charles Bridge' },
    { country: 'Central African Republic', emojis: '🇨🇫 🌍 🏞️', famousLandmark: 'Manovo-Gounda St. Floris National Park' },
    { country: 'Cuba', emojis: '🇨🇺 🏝️ 🎺', famousLandmark: 'Havana Old Town' },
    { country: 'Cyprus', emojis: '🇨🇾 🌊 🏛️', famousLandmark: 'Tombs of the Kings' },
    { country: 'Costa Rica', emojis: '🇨🇷 🏞️ 🐒', famousLandmark: 'Arenal Volcano' },
    { country: 'Congo', emojis: '🇨🇬 🌍 🏞️', famousLandmark: 'Lesio-Louna Gorilla Reserve' },
    { country: 'DPRK', emojis: '🇰🇵 🌍 ⛩️', famousLandmark: 'Mount Paektu' },
    { country: 'Dominica', emojis: '🇩🇲 🏞️ ⛰️', famousLandmark: 'Boiling Lake' },
    { country: 'Dominican Republic', emojis: '🇩🇴 🏝️ 🏰', famousLandmark: 'Santo Domingo Colonial Zone' },
    { country: 'Djibouti', emojis: '🇩🇯 🏝️ 🏜️', famousLandmark: 'Lake Assal' },
    { country: 'Denmark', emojis: '🇩🇰 🏰 🌊', famousLandmark: 'The Little Mermaid' },
    { country: 'DRC', emojis: '🇨🇩 🌍 🏞️', famousLandmark: 'Virunga National Park' },
    { country: 'Ethiopia', emojis: '🇪🇹 🌍 🏰', famousLandmark: 'Rock-Hewn Churches of Lalibela' },
    { country: 'El Salvador', emojis: '🇸🇻 🏝️ 🌋', famousLandmark: 'Coatepeque Lake' },
    { country: 'Egypt', emojis: '🏜️ 🐫 🌅', famousLandmark: 'Pyramids of Giza' },
    { country: 'Ecuador', emojis: '🇪🇨 🏞️ 🦎', famousLandmark: 'Galápagos Islands' },
    { country: 'Eswatini', emojis: '🇸🇿 🌍 ⛰️', famousLandmark: 'Mlilwane Wildlife Sanctuary' },
    { country: 'Estonia', emojis: '🇪🇪 🏰 🌲', famousLandmark: 'Tallinn Old Town' },
    { country: 'Eritrea', emojis: '🇪🇷 🌍 🏞️', famousLandmark: 'Dahlak Archipelago' },
    { country: 'Equatorial Guinea', emojis: '🇬🇶 🌍 🏞️', famousLandmark: 'Pico Basile' },
    { country: 'Faroe Islands', emojis: '🇫🇴 ⛰️ 🏞️', famousLandmark: 'Mulafossur Waterfall' },
    { country: 'Finland', emojis: '🇫🇮 ❄️ 🏞️', famousLandmark: 'Helsinki Cathedral' },
    { country: 'Fiji', emojis: '🇫🇯 🏝️ 🐠', famousLandmark: 'Yasawa Islands' },
    { country: 'Gabon', emojis: '🇬🇦 🏞️ 🦍', famousLandmark: 'Ivindo National Park' },
    { country: 'Gambia', emojis: '🇬🇲 🏞️ 🏝️', famousLandmark: 'Abuko Nature Reserve' },
    { country: 'Greece', emojis: '🇬🇷 🏛️ 🏝️', famousLandmark: 'Acropolis of Athens' },
    { country: 'Grenada', emojis: '🇬🇩 🏝️ ⛵', famousLandmark: 'Grand Anse Beach' },
    { country: 'Greenland', emojis: '🇬🇱 ❄️ 🏞️', famousLandmark: 'Ilulissat Icefjord' },
    { country: 'Guinea-Bissau', emojis: '🇬🇼 🌍 🏝️', famousLandmark: 'Orango Island' },
    { country: 'Ghana', emojis: '🇬🇭 🌍 🏰', famousLandmark: 'Cape Coast Castle' },
    { country: 'Guatemala', emojis: '🇬🇹 🏞️ 🌋', famousLandmark: 'Tikal National Park' },
    { country: 'Georgia', emojis: '🇬🇪 🏞️ 🏰', famousLandmark: 'Gergeti Trinity Church' },
    { country: 'Guyana', emojis: '🇬🇾 🏞️ 🌎', famousLandmark: 'Kaieteur Falls' },
    { country: 'Haiti', emojis: '🇭🇹 🏞️ 🏝️', famousLandmark: 'Citadelle Laferrière' },
    { country: 'Honduras', emojis: '🇭🇳 🏝️ 🌊', famousLandmark: 'Copán Ruins' },
    { country: 'Holy See', emojis: '🇻🇦 ⛪ 🏞️', famousLandmark: 'St. Peters Basilica' },
    { country: 'Hungary', emojis: '🇭🇺 ⛪ 🏰', famousLandmark: 'Fisherman’s Bastion' },
    { country: 'Israel', emojis: '🕍 🌍 🌺', famousLandmark: 'Western Wall' },
    { country: 'Ireland', emojis: '☘️ 🍺 🏰', famousLandmark: 'Cliffs of Moher' },
    { country: 'Iran', emojis: '🇮🇷 🏰 ⛰️', famousLandmark: 'Persepolis' },
    { country: 'Iraq', emojis: '🇮🇶 🏞️ 🕌', famousLandmark: 'Ziggurat of Ur' },
    { country: 'Indonesia', emojis: '🇮🇩 🏝️ 🦎', famousLandmark: 'Borobudur Temple' },
    { country: 'India', emojis: '🕌 🍛 🐘', famousLandmark: 'Taj Mahal' },
    { country: 'Italy', emojis: '🇮🇹 🏰 ⛰️', famousLandmark: 'Colosseum' },
    { country: 'Iceland', emojis: '❄️ 🇮🇸 🌋', famousLandmark: 'Blue Lagoon' },
    { country: 'Ivory Coast', emojis: '🇨🇮 🌍 🏞️', famousLandmark: 'Mount Nimba Strict Nature Reserve' },
    { country: 'Japan', emojis: '🗾 🏯 🍣', famousLandmark: 'Mount Fuji' },
    { country: 'Jamaica', emojis: '🇯🇲 🏝️ 🎶', famousLandmark: 'Dunns River Falls' },
    { country: 'Jordan', emojis: '🇯🇴 🏞️ 🕌', famousLandmark: 'Petra' },
    { country: 'Kazakhstan', emojis: '🇰🇿 🏞️ 🏰', famousLandmark: 'Charyn Canyon' },
    { country: 'Kenya', emojis: '🦓 🌍 🐘', famousLandmark: 'Maasai Mara National Reserve' },
    { country: 'Kiribati', emojis: '🇰🇮 🏝️ 🌊', famousLandmark: 'Phoenix Islands Protected Area' },
    { country: 'Kyrgyzstan', emojis: '🇰🇬 🏔️ 🐎', famousLandmark: 'Issyk-Kul Lake' },
    { country: 'Kuwait', emojis: '🇰🇼 🏝️ 🕌', famousLandmark: 'Kuwait Towers' },
    { country: 'Libya', emojis: '🇱🇾 🌍 🏜️', famousLandmark: 'Leptis Magna' },
    { country: 'Liberia', emojis: '🇱🇷 🌍 🏞️', famousLandmark: 'Sapo National Park' },
    { country: 'Laos', emojis: '🇱🇦 🏞️ 🏯', famousLandmark: 'Luang Prabang' },
    { country: 'Lebanon', emojis: '🇱🇧 🏞️ 🏰', famousLandmark: 'Byblos' },
    { country: 'Lesotho', emojis: '🇱🇸 🏞️ ⛰️', famousLandmark: 'Maletsunyane Falls' },
    { country: 'Latvia', emojis: '🇱🇻 🏰 🌲', famousLandmark: 'Rundāle Palace' },
    { country: 'Lithuania', emojis: '🇱🇹 🏰 🌲', famousLandmark: 'Trakai Island Castle' },
    { country: 'Luxembourg', emojis: '🇱🇺 🏰 🌲', famousLandmark: 'Luxembourg City' },
    { country: 'Liechtenstein', emojis: '🇱🇮 ⛰️ 🏰', famousLandmark: 'Vaduz Castle' },
    { country: 'Madagascar', emojis: '🇲🇬 🏝️ 🐵', famousLandmark: 'Avenue of the Baobabs' },
    { country: 'Mali', emojis: '🇲🇱 🌍 🏰', famousLandmark: 'Great Mosque of Djenne' },
    { country: 'Mongolia', emojis: '🇲🇳 🏞️ 🐎', famousLandmark: 'Khustain Nuruu National Park' },
    { country: 'Micronesia', emojis: '🇫🇲 🏝️ 🏞️', famousLandmark: 'Nan Madol' },
    { country: 'Marshall Islands', emojis: '🇲🇭 🏝️ 🌊', famousLandmark: 'Bikini Atoll' },
    { country: 'Mozambique', emojis: '🇲🇿 🌍 🏝️', famousLandmark: 'Bazaruto Archipelago' },
    { country: 'Myanmar', emojis: '🇲🇲 🏞️ 🛕', famousLandmark: 'Bagan Temples' },
    { country: 'Monaco', emojis: '🇲🇨 🏰 🏖️', famousLandmark: 'Monte Carlo Casino' },
    { country: 'Morocco', emojis: '🕌 🐪 🌵', famousLandmark: 'Chefchaouen' },
    { country: 'Maldives', emojis: '🏝️ 🐠 🌅', famousLandmark: 'Ari Atoll' },
    { country: 'Mexico', emojis: '🌮 🌶️ 🎺', famousLandmark: 'Chichen Itza' },
    { country: 'Malawi', emojis: '🇲🇼 🌍 🏞️', famousLandmark: 'Lake Malawi' },
    { country: 'Mauritania', emojis: '🇲🇷 🏜️ 🐪', famousLandmark: 'Banc dArguin National Park' },
    { country: 'Mauritius', emojis: '🇲🇺 🏝️ 🌺', famousLandmark: 'Seven Colored Earths' },
    { country: 'Malaysia', emojis: '🇲🇾 🏞️ 🌅', famousLandmark: 'Petronas Towers' },
    { country: 'Montenegro', emojis: '🇲🇪 🏞️ 🏰', famousLandmark: 'Bay of Kotor' },
    { country: 'Malta', emojis: '🇲🇹 🏰 🌊', famousLandmark: 'Megalithic Temples' },
    { country: 'Moldova', emojis: '🇲🇩 🏰 🍇', famousLandmark: 'Mileștii Mici Wine Cellars' },
    { country: 'Nauru', emojis: '🇳🇷 🏝️ 🏞️', famousLandmark: 'Buada Lagoon' },
    { country: 'Norway', emojis: '🏔️ 🎣 ❄️', famousLandmark: 'The Northern Lights' },
    { country: 'North Macedonia', emojis: '🇲🇰 🏰 🏞️', famousLandmark: 'Ohrid Old Town' },
    { country: 'North Korea', emojis: '🇰🇵 🏯 🌍', famousLandmark: 'Mount Paektu' },
    { country: 'Netherlands', emojis: '🌷 🚲 🧀', famousLandmark: 'Van Gogh Museum' },
    { country: 'Namibia', emojis: '🇳🇦 🏜️ 🦓', famousLandmark: 'Sossusvlei' },
    { country: 'Nigeria', emojis: '🇳🇬 🌍 🏰', famousLandmark: 'Zuma Rock' },
    { country: 'New Caledonia', emojis: '🏝️ 🐠 🌺', famousLandmark: 'Heart of Voh' },
    { country: 'New Zealand', emojis: '🇳🇿 🏞️ 🐑', famousLandmark: 'Māori Culture' },
    { country: 'Nepal', emojis: '🇳🇵 🏔️ 🌅', famousLandmark: 'Everest Base Camp' },
    { country: 'Niger', emojis: '🇳🇪 🌍 🏰', famousLandmark: 'Agadez Mosque' },
    { country: 'Nicaragua', emojis: '🇳🇮 🏝️ 🏞️', famousLandmark: 'Ometepe Island' },
    { country: 'Oman', emojis: '🇴🇲 🏜️ 🕌', famousLandmark: 'Sultan Qaboos Grand Mosque' },
    { country: 'Peru', emojis: '🏞️ 🥔 🇵🇪', famousLandmark: 'Machu Picchu' },
    { country: 'Palau', emojis: '🇵🇼 🏝️ 🐠', famousLandmark: 'Rock Islands' },
    { country: 'Panama', emojis: '🇵🇦 🏝️ 🌊', famousLandmark: 'Panama Canal' },
    { country: 'Papua New Guinea', emojis: '🇵🇬 🏝️ 🗿', famousLandmark: 'Kuk Early Agricultural Site' },
    { country: 'Pakistan', emojis: '🇵🇰 🏞️ 🕌', famousLandmark: 'Badshahi Mosque' },
    { country: 'Paraguay', emojis: '🇵🇾 🏞️ 🌊', famousLandmark: 'Iguazu Falls' },
    { country: 'Poland', emojis: '🇵🇱 🏰 🏞️', famousLandmark: 'Wieliczka Salt Mine' },
    { country: 'Portugal', emojis: '🍷 🏰 🌊', famousLandmark: 'Belem Tower' },
    { country: 'Philippines', emojis: '🇵🇭 🏝️ 🌅', famousLandmark: 'Banaue Rice Terraces' },
    { country: 'Qatar', emojis: '🇶🇦 🏝️ 🕌', famousLandmark: 'The Pearl-Qatar' },
    { country: 'Romania', emojis: '🇷🇴 ⛰️ 🏰', famousLandmark: 'Peles Castle' },
    { country: 'Russia', emojis: '🇷🇺 ❄️ 🏰', famousLandmark: 'Red Square' },
    { country: 'Rwanda', emojis: '🇷🇼 🌍 🏞️', famousLandmark: 'Volcanoes National Park' },
    { country: 'São Tomé and Príncipe', emojis: '🇸🇹 🏝️ 🌊', famousLandmark: 'Pico Cão Grande' },
    { country: 'Saint Lucia', emojis: '🇱🇨 🏝️ 🏰', famousLandmark: 'Pitons' },
    { country: 'Saint Vincent and the Grenadines', emojis: '🇻🇨 🏝️ ⛵', famousLandmark: 'Tobago Cays' },
    { country: 'Saint Kitts and Nevis', emojis: '🇰🇳 🏝️ 🏰', famousLandmark: 'Brimstone Hill Fortress' },
    { country: 'Samoa', emojis: '🇼🇸 🏝️ 🌺', famousLandmark: 'To Sua Ocean Trench' },
    { country: 'San Marino', emojis: '🇸🇲 ⛰️ 🏰', famousLandmark: 'Guaita' },
    { country: 'Sweden', emojis: '🇸🇪 🧑‍🎨 ❄️', famousLandmark: 'Vasa Museum' },
    { country: 'Sierra Leone', emojis: '🇸🇱 🏝️ 🏞️', famousLandmark: 'Tiwai Island' },
    { country: 'Slovakia', emojis: '🇸🇰 🏰 🏞️', famousLandmark: 'Spis Castle' },
    { country: 'Senegal', emojis: '🇸🇳 🌍 🏰', famousLandmark: 'Goree Island' },
    { country: 'Slovenia', emojis: '🇸🇮 🏞️ 🏰', famousLandmark: 'Lake Bled' },
    { country: 'Scotland', emojis: '🏴󠁧󠁢󠁳󠁣󠁴󠁿 🏰 🌊', famousLandmark: 'Loch Ness' },
    { country: 'Sri Lanka', emojis: '🇱🇰 🏝️ 🌅', famousLandmark: 'Sigiriya' },
    { country: 'Switzerland', emojis: '🏔️ 🧀 ⛷️', famousLandmark: 'Matterhorn' },
    { country: 'Singapore', emojis: '🏙️ 🍜 🏝️', famousLandmark: 'Marina Bay Sands' },
    { country: 'Saudi Arabia', emojis: '🇸🇦 🏜️ 🕌', famousLandmark: 'Al-Masjid an-Nabawi' },
    { country: 'South Africa', emojis: '🦓 🌍 🦁', famousLandmark: 'Table Mountain' },
    { country: 'South Korea', emojis: '🇰🇷 🏯 🌸', famousLandmark: 'Gyeongbokgung Palace' },
    { country: 'South Sudan', emojis: '🇸🇸 🌍 🏞️', famousLandmark: 'Boma National Park' },
    { country: 'Serbia', emojis: '🇷🇸 🏰 🏞️', famousLandmark: 'Belgrade Fortress' },
    { country: 'Seychelles', emojis: '🇸🇨 🏝️ 🐢', famousLandmark: 'Vallée de Mai' },
    { country: 'Syria', emojis: '🇸🇾 🏰 🌍', famousLandmark: 'Palmyra' },
    { country: 'State of Palestine', emojis: '🇵🇸 🕌 🌍', famousLandmark: 'Dome of the Rock' },
    { country: 'Spain', emojis: '🇪🇸 🏰 🏞️', famousLandmark: 'Sagrada Familia' },
    { country: 'Somalia', emojis: '🇸🇴 🌍 🏝️', famousLandmark: 'Jazeera Beach' },
    { country: 'Suriname', emojis: '🇸🇷 🏞️ 🌊', famousLandmark: 'Brownsberg Nature Park' },
    { country: 'Sudan', emojis: '🇸🇩 🏜️ 🏛️', famousLandmark: 'Pyramids of Meroe' },
    { country: 'Solomon Islands', emojis: '🇸🇧 🏝️ 🐠', famousLandmark: 'Marovo Lagoon' },
    { country: 'Tajikistan', emojis: '🇹🇯 🏔️ 🕌', famousLandmark: 'Ismaili Centre' },
    { country: 'Taiwan', emojis: '🇹🇼 🌆 🏞️', famousLandmark: 'Taroko National Park' },
    { country: 'Timor-Leste', emojis: '🇹🇱 🏝️ 🌋', famousLandmark: 'Mount Ramelau' },
    { country: 'Trinidad and Tobago', emojis: '🇹🇹 🏝️ 🍹', famousLandmark: 'Maracas Beach' },
    { country: 'Turkey', emojis: '🦃 🕌 ☕', famousLandmark: 'Hagia Sophia' },
    { country: 'Thailand', emojis: '🌴 🍜 🐘', famousLandmark: 'Wat Arun' },
    { country: 'Tanzania', emojis: '🇹🇿 🏞️ 🐘', famousLandmark: 'Mount Kilimanjaro' },
    { country: 'Tunisia', emojis: '🇹🇳 🏜️ 🕌', famousLandmark: 'Carthage Ruins' },
    { country: 'The Bahamas', emojis: '🇧🇸 🏝️ 🏖️', famousLandmark: 'Exuma Cays Land and Sea Park' },
    { country: 'Togo', emojis: '🇹🇬 🌍 🏖️', famousLandmark: 'Cascade de Womé' },
    { country: 'Tonga', emojis: '🇹🇴 🏝️ 🐋', famousLandmark: 'Ha\'amonga \'a Maui' },
    { country: 'Turkmenistan', emojis: '🇹🇲 🏞️ 🏰', famousLandmark: 'Darvaza Gas Crater' },
    { country: 'Tuvalu', emojis: '🇹🇻 🏝️ 🌊', famousLandmark: 'Funafuti Atoll' },
    { country: 'UK', emojis: '🇬🇧 🏰 🌊', famousLandmark: 'Stonehenge' },
    { country: 'USA', emojis: '🇺🇸 🏞️ 🏰', famousLandmark: 'Grand Canyon' },
    { country: 'Ukraine', emojis: '🇺🇦 🏰 🌊', famousLandmark: 'Saint Sophias Cathedral' },
    { country: 'Uzbekistan', emojis: '🇺🇿 🕌 🏞️', famousLandmark: 'Registan Square' },
    { country: 'Uganda', emojis: '🇺🇬 🌍 🏞️', famousLandmark: 'Bwindi Impenetrable Forest' },
    { country: 'Uruguay', emojis: '🇺🇾 🏖️ 🍷', famousLandmark: 'Casapueblo' },
    { country: 'United Arab Emirates', emojis: '🇦🇪 🏝️ 🌐', famousLandmark: 'Burj Khalifa' },
    { country: 'Vanuatu', emojis: '🇻🇺 🏝️ 🌋', famousLandmark: 'Mount Yasur' },
    { country: 'Vatican City', emojis: '🇻🇦 ⛪ 🏰', famousLandmark: 'St. Peter\'s Basilica' },
    { country: 'Vietnam', emojis: '🇻🇳 🍜 🎏', famousLandmark: 'Halong Bay' },
    { country: 'Yemen', emojis: '🇾🇪 🏜️ 🕌', famousLandmark: 'Rock Palace of Wadi Dhar' },
    { country: 'Zambia', emojis: '🇿🇲 🏞️ 🐘', famousLandmark: 'Victoria Falls' },
    { country: 'Zimbabwe', emojis: '🇿🇼 🏞️ 🦏', famousLandmark: 'Victoria Falls' },
  ];

  return (
    <div className="virtual-travel-container">
      <h1>Virtual Emoji Tour</h1>
      {additionalTravelExperiences.map((experience, index) => (
        <TravelExperience key={index} {...experience} />
      ))}
    </div>
  );
};

export default VirtualTravel;